Repository adobecom/bacom-blog, pull requests merged in 2024-07, with the labels that each got.

#59 Revert "[MWPW 151457] Added stage domains map to make links environment-aware"
  blog/scripts/scripts.js
Labels: verified

#61 MWPW-154170 Kodiak - ignore *.env just in case
  .gitignore
Labels: trivial

#62 MWPW-145389 Push sync for floodgate
  .github/workflows/fg-sync-repos.yml
Labels: zero-impact
